---
title: "db_forms"
author: "Jake Eisaguirre"
date: "2022-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages

librarian::shelf(tidyverse, here, janitor, sf, lubridate, RPostgres, rstudioapi, DBI, oce, leaflet, sfheaders)
```


# db connection
```{r}

tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv, 
                 dbname = Sys.getenv("dbname"),
                 host = Sys.getenv("host"), 
                 port = Sys.getenv("port"),
                 user = Sys.getenv("user"), 
                 password = Sys.getenv("password"))
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })


```

```{r}

dbExecute(connection, "set search_path = survey_data")

dbListTables(connection)

a <- dbGetQuery(connection, "Select * from location where location = 'panama'")

```

```{r}

sql_loc <- "Select * from location where location = ?location"

loc_q <- sqlInterpolate(ANSI(), sql_loc, location = 'usa')

loc_out <- dbGetQuery(connection, loc_q)

sql_reg <- "Select * from region where region = ?region"

loc_r <- sqlInterpolate(ANSI(), sql_reg, region = 'new_mexico')

reg_out <- dbGetQuery(connection, loc_r)

loc_reg <- left_join(loc_out, reg_out, by = c("location_id"))



```


```{r}

loc_r <- glue::glue_data_sql(
      
      "SELECT * FROM region
       WHERE region IN ({reg_name*})",
      reg_name = c("new_mexico", "california"),
      .con = connection)
    
    reg_out <- as.data.frame(dbGetQuery(connection, loc_r))

```

```{r}


 t <- location %>%
      left_join(region, by = c("location_id")) %>%
      left_join(site, by = c("region_id")) %>%
      left_join(visit, by = c("site_id")) %>%
      left_join(survey, by = c("visit_id")) %>% 
      left_join(capture, by = c("penn_survey_id"))

t <- capture %>% 
  left_join(penn_survey, by = c("penn_survey_id")) 
  left_join(brazil_legacy_survey, by = c("brazil_survey_id"))

```


```{r}

 t <- location %>%
      left_join(region, by = c("location_id"))%>%
      left_join(site, by = c("region_id"))%>%
      left_join(visit, by = c("site_id")) %>%
      left_join(survey, by = c("visit_id")) 
a <- t %>% 
      left_join(capture, by = c("survey_id"))
```


```{r}

cap <- full_cap_data %>% collect()

b <- cap %>% 
  filter(year %in% c(2020:2022),
             location %in% c("brazil"),
             region %in% c("boraceia", "santa_virginia"),
             site %in% c("b3t", "lago_sede_water")) %>% 
  janitor::remove_empty(which = "cols") %>% 
        colnames() %>% 
        as.data.frame() %>%
  rename("Variables" = ".") %>% 
  filter(!Variables == "location" &
         !Variables == "region" &
         !Variables == "site" &
         !Variables == "year")

```

```{r}

data <- no_pros_cap_data %>% 
  filter(year %in% c(2014:2023),
             location %in% c("usa"),
             region %in% c("california")) %>% 
  select(year, location, region, species_capture) %>%
  group_by(year, location, region, species_capture) %>%
  summarise(count = n()) %>% 
  collect() %>% 
  ungroup() %>% 
  select(!c(location, region)) %>% 
  mutate(count = as.numeric(count)) %>% 
  filter(!species_capture %in% c("?", "control", "controle", NA))


ggplot(data = data, aes(x = species_capture, y = count, fill = factor(year))) +   
  geom_col(position = position_dodge2(preserve = "single")) +   
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.3)) 




ggplot(data = data, aes(x = year, y = med, fill = factor(year))) +
   geom_col(position = "dodge2")+
   theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
   facet_wrap(vars(species_capture), scales = "free_y")  

data$species_capture_year = paste0(data$species_capture,"-",data$year)

ggplot(data = data, aes(x = species_capture_year, y = count, fill = factor(year))) +
   geom_col(position = "dodge2")+
   theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
data <- full_cap_data %>% 
  filter(year %in% c(2014:2023),
             location %in% c("panama"),
             region %in% c("el_cope")) %>% 
  select(year, location, region, bd_swab_id, genetic_id, microbiome_swab_id, amp_id, mucosome_id,
         bacterial_swab_id, antibody_id, crispr_id) %>% 
  group_by(year, location, region) %>% 
  summarise(bd_swab_id_count = as.numeric(count(bd_swab_id)),
            genetic_id_count = as.numeric(count(genetic_id)),
            microbiome_swab_id_count = as.numeric(count(microbiome_swab_id)),
            amp_id_count = as.numeric(count(amp_id)),
            mucosome_id_count = as.numeric(count(mucosome_id)),
            bacterial_swab_id_count = as.numeric(count(bacterial_swab_id)),
            antibody_id_count = as.numeric(count(antibody_id)),
            crispr_id_count = as.numeric(count(crispr_id))) %>% 
  collect() %>% 
  ungroup() %>% 
  select(!c(location, region)) %>% 
  pivot_longer(!year, names_to = "swab_type", values_to = "count")


ggplot(data = data, aes(x = factor(year), y = count, fill = swab_type )) +   
  geom_point(aes(color = swab_type)) +   
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.3)) 
```

```{r}

tally_data <- no_pros_cap_data %>% 
  filter(year %in% c(1995:2023)) %>% 
  select(year, site, species_capture, bd_swab_id, genetic_id, microbiome_swab_id, amp_id, mucosome_id,
         bacterial_swab_id, antibody_id, crispr_id) %>%
  group_by(site, year) %>%
  summarise(species_count = count(species_capture),
            bd_swab_tally = count(bd_swab_id),
            genetic_tally = count(genetic_id),
            microbiome_tally = count(microbiome_swab_id),
            amp_tally = count(amp_id),
            mucosome_tally = count(mucosome_id),
            bacterial_tally = count(bacterial_swab_id),
            anti_tally = count(antibody_id),
            crispr_tally = count(crispr_id)) %>% 
  collect()

spat_data <- no_pros_cap_data %>% 
  filter(year %in% c(1995:2023)) %>% 
  select(location, region, site, utme, utmn, utm_zone) %>% 
  group_by(site) %>% 
  distinct() %>% 
  collect()

  
spat <- utm2lonlat(spat_data$utme, spat_data$utmn, zone = spat_data$utm_zone) %>% 
  as.data.frame()

spat_data$lat <- spat$latitude

spat_data$lon <- spat$longitude

fin_spat <- select(spat_data, !c(utme, utmn, utm_zone))

box <- fin_spat %>% 
  filter(location == "usa")

b <- st_bbox(c(xmin = min(box$lon, na.rm = T), xmax = max(box$lon, na.rm = T), ymin = min(box$lat, na.rm = T), 
               ymax = max(box$lat, na.rm = T)))

leaflet() %>% 
  addProviderTiles("Esri.WorldImagery") %>% 
  addCircleMarkers(data = fin_spat, lng = ~lon, lat = ~lat,
             label = ~site, 
             clusterOptions = markerClusterOptions(zoomToBoundsOnClick = T,
                                                   spiderfyOnMaxZoom = T,
                                                   freezeAtZoom = F,
                                                   spiderfyDistanceMultiplier=5),
             color = "#35b779", radius = 3, opacity = 1, fillOpacity = 1, weight = 5)


```

```{r}

loc_box_wrangle <- no_pros_cap_data %>% 
  filter(year %in% c(1995:2023),
         location == "brazil") %>% 
  select(location, site, year, utme, utmn, utm_zone) %>% 
  group_by(site) %>% 
  distinct() %>% 
  collect() %>% 
  drop_na()



loc_box_con <- utm2lonlat(loc_box_wrangle$utme, loc_box_wrangle$utmn, zone = loc_box_wrangle$utm_zone) %>% 
  as.data.frame()

loc_box_wrangle$lat <- loc_box_con$latitude

loc_box_wrangle$lon <- loc_box_con$longitude

fin_box_spat_loc <- select(loc_box_wrangle, !c(utme, utmn, utm_zone))

loc_box <-  st_as_sf(fin_box_spat_loc, coords = c("lat", "lon")) %>% 
  st_bbox(geometry) %>% 
  as.vector()

```

## polygon creation
```{r}

polygons <- tbl(survey_data_connection, "location") %>%
  inner_join(tbl(survey_data_connection, "region"), by = c("location_id")) %>%
  inner_join(tbl(survey_data_connection, "site"), by = c("region_id")) %>% 
  collect()

spat <- utm2lonlat(polygons$utme, polygons$utmn, zone = polygons$utm_zone) %>% 
  as.data.frame()

polygons$lat <- spat$latitude

polygons$lon <- spat$longitude

fin_spat <- select(polygons, !c(utme, utmn, utm_zone)) %>% 
  drop_na(c(lat, lon))%>% 
  select(location, lat, lon)
  
poly <- sfheaders::sf_polygon(fin_spat, x = "lon", y = "lat", polygon_id = "region")  
  
  
st_as_sf(coords = c("lat", "lon"), crs = 4326) %>% 
  select(region, geometry) %>% 
  group_by(region) %>% 
  summarize(geometry = st_combine(geometry)) %>% 
  st_cast("POLYGON")

plot(fin_spat$geometry[1])
```

