---
title: "db_forms"
author: "Jake Eisaguirre"
date: "2022-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages

librarian::shelf(tidyverse, here, janitor, sf, lubridate, RPostgres, rstudioapi, DBI)
```


# db connection
```{r}

tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv, 
                 dbname = Sys.getenv("dbname"),
                 host = Sys.getenv("host"), 
                 port = Sys.getenv("port"),
                 user = Sys.getenv("user"), 
                 password = Sys.getenv("password"))
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })


```

```{r}

dbExecute(connection, "set search_path = survey_data")

dbListTables(connection)

a <- dbGetQuery(connection, "Select * from location where location = 'panama'")

```

```{r}

sql_loc <- "Select * from location where location = ?location"

loc_q <- sqlInterpolate(ANSI(), sql_loc, location = 'usa')

loc_out <- dbGetQuery(connection, loc_q)

sql_reg <- "Select * from region where region = ?region"

loc_r <- sqlInterpolate(ANSI(), sql_reg, region = 'new_mexico')

reg_out <- dbGetQuery(connection, loc_r)

loc_reg <- left_join(loc_out, reg_out, by = c("location_id"))



```


```{r}

loc_r <- glue::glue_data_sql(
      
      "SELECT * FROM region
       WHERE region IN ({reg_name*})",
      reg_name = c("new_mexico", "california"),
      .con = connection)
    
    reg_out <- as.data.frame(dbGetQuery(connection, loc_r))

```

```{r}


 t <- location %>%
      left_join(region, by = c("location_id")) %>%
      left_join(site, by = c("region_id")) %>%
      left_join(visit, by = c("site_id")) %>%
      left_join(survey, by = c("visit_id")) %>% 
      left_join(capture, by = c("penn_survey_id"))

t <- capture %>% 
  left_join(penn_survey, by = c("penn_survey_id")) 
  left_join(brazil_legacy_survey, by = c("brazil_survey_id"))

```


```{r}

 t <- location %>%
      left_join(region, by = c("location_id"))%>%
      left_join(site, by = c("region_id"))%>%
      left_join(visit, by = c("site_id")) %>%
      left_join(survey, by = c("visit_id")) 
a <- t %>% 
      left_join(capture, by = c("survey_id"))
```


```{r}

b <- cap %>% 
  filter(year %in% c(2020:2022),
             location %in% c("brazil"),
             region %in% c("boraceia", "santa_virginia"),
             site %in% c("b3t", "lago_sede_water")) %>% 
  remove_empty(which = "cols")

```

